# Generated by Django 6.0.7 on 2026-07-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_assigned_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
